import jsPDF from 'jspdf';
import 'jspdf-autotable';

/**
 * Exports structured notes to a styled PDF file.
 * @param {Object} notes - The notes object from OpenAI
 */
export function exportToPDF(notes) {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const pageW = doc.internal.pageSize.getWidth();
  const margin = 20;
  const contentW = pageW - margin * 2;
  let y = margin;

  // Helper: add page if needed
  const checkPage = (height = 10) => {
    if (y + height > doc.internal.pageSize.getHeight() - margin) {
      doc.addPage();
      y = margin;
    }
  };

  // Header bar
  doc.setFillColor(30, 20, 60);
  doc.rect(0, 0, pageW, 38, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  const title = notes.title || 'Smart Notes';
  doc.text(title, margin, 18);

  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(180, 170, 255);
  doc.text('Generated by Smart Notes Generator', margin, 25);
  doc.text(`${new Date().toLocaleString()}`, margin, 31);

  y = 50;
  doc.setTextColor(30, 30, 50);

  // Summary section
  if (notes.summary) {
    doc.setFillColor(245, 243, 255);
    doc.roundedRect(margin, y, contentW, 0, 2, 2, 'F');
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(100, 85, 200);
    doc.text('SUMMARY', margin, y + 7);
    y += 12;

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(50, 50, 70);
    const summaryLines = doc.splitTextToSize(notes.summary, contentW);
    doc.text(summaryLines, margin, y);
    y += summaryLines.length * 5.5 + 10;
  }

  // Key Points
  if (notes.keyPoints?.length > 0) {
    checkPage(20);
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(100, 85, 200);
    doc.text('KEY POINTS', margin, y);
    y += 7;

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(50, 50, 70);

    notes.keyPoints.forEach((point) => {
      checkPage(8);
      const lines = doc.splitTextToSize(`• ${point}`, contentW - 4);
      doc.text(lines, margin + 2, y);
      y += lines.length * 5.5 + 2;
    });
    y += 6;
  }

  // Sections
  if (notes.sections?.length > 0) {
    notes.sections.forEach((section) => {
      checkPage(16);
      // Section heading
      doc.setFontSize(11);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(100, 85, 200);
      doc.text(section.heading?.toUpperCase() || 'SECTION', margin, y);
      // Underline
      doc.setDrawColor(180, 160, 255);
      doc.setLineWidth(0.4);
      doc.line(margin, y + 1.5, margin + contentW, y + 1.5);
      y += 8;

      if (section.content) {
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(10);
        doc.setTextColor(50, 50, 70);
        const lines = doc.splitTextToSize(section.content, contentW);
        checkPage(lines.length * 5.5);
        doc.text(lines, margin, y);
        y += lines.length * 5.5 + 4;
      }

      if (section.bullets?.length > 0) {
        section.bullets.forEach((bullet) => {
          checkPage(8);
          doc.setFont('helvetica', 'normal');
          doc.setFontSize(9.5);
          doc.setTextColor(60, 60, 80);
          const lines = doc.splitTextToSize(`◦ ${bullet}`, contentW - 6);
          doc.text(lines, margin + 4, y);
          y += lines.length * 5 + 2;
        });
      }
      y += 6;
    });
  }

  // Action Items
  if (notes.actionItems?.length > 0) {
    checkPage(20);
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(200, 100, 50);
    doc.text('ACTION ITEMS', margin, y);
    y += 7;
    notes.actionItems.forEach((item) => {
      checkPage(8);
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(10);
      doc.setTextColor(50, 50, 70);
      const lines = doc.splitTextToSize(`☐ ${item}`, contentW - 4);
      doc.text(lines, margin + 2, y);
      y += lines.length * 5.5 + 2;
    });
    y += 6;
  }

  // Tags
  if (notes.tags?.length > 0) {
    checkPage(12);
    doc.setFontSize(9);
    doc.setFont('helvetica', 'italic');
    doc.setTextColor(130, 120, 180);
    doc.text('Tags: ' + notes.tags.map((t) => `#${t}`).join('  '), margin, y);
    y += 8;
  }

  // Footer with page numbers
  const totalPages = doc.internal.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(180, 180, 200);
    doc.setFont('helvetica', 'normal');
    doc.text(
      `Page ${i} of ${totalPages}  •  Smart Notes Generator`,
      pageW / 2,
      doc.internal.pageSize.getHeight() - 10,
      { align: 'center' }
    );
  }

  const filename = `${(notes.title || 'notes').replace(/[^a-z0-9]/gi, '_').toLowerCase()}_${Date.now()}.pdf`;
  doc.save(filename);
}
